go.mod, go.sum
Downgrading for now so I can run it with go-ipfs. Still using a  local fork with upgraded go-filestore as I don't want to downgrade go-data-transfer.
=> Downgrade libp2p-core to v0.7.0 for compatibility with go-ipfs

exchange.go, exchange_test.go, go.mod, session.go, supply/supply.go, supply/supply_test.go, testutil/mocknet.go
Learnings: the exchange interface defies the purpose of using GraphSync to exchange blocks because DAG.Get operations will trigger multiple GetBlock operations which all result in individual GraphSync requests. This will impact our decision to support the block exchange interface.
=> feat(test): exchange with the ipfs block and dag service

cmd/hop/cli/start.go, exchange.go, exchange_test.go, node/hopn.go, node/server.go, options.go, session.go, supply/network.go, supply/network_test.go, supply/regions.go, supply/supply.go, supply/supply_test.go
Here we enable the grouping of Myel nodes within different preset and custom regions. This allows partitioning of the network to target the right providers.
=> feat:  basic and custom regions

cmd/hop/cli/cli.go, cmd/hop/cli/commit.go, cmd/hop/cli/status.go, exchange.go, exchange_test.go, go.mod, node/hopn.go, node/message.go, node/node_test.go, node/workdag.go, node/workdag_test.go, options.go, retrieval/client/fsm.go, retrieval/environments.go, retrieval/gsconfig.go, retrieval/manager.go, retrieval/manager_test.go, retrieval/provider/fsm.go, retrieval/validators.go, session.go, supply/manifest.go, supply/manifest_test.go, supply/supply.go, supply/supply_test.go, testutil/mocknet.go
Here we introduce a new workflow inspired from git:
Once can use the cli to add multiple files to the 'workdag' and commit them into a single archive for storage. This makes it easier to storing multiple files onto the network. Further we enforce independent stores for each 'workdag'.
=> feat: prep DAG for storage

README.md
Mostly for the usage section, which with the `sh` tag was rendering some stuff in it with syntax highlighting.
=> Add more appropriate markdown blocks

filecoin/filecoin.go, filecoin/lotus.go, filecoin/testutils.go, filecoin/types.go, payments/channel.go, payments/manager.go, payments/manager_test.go, payments/store.go, retrieval/deal/types.go, retrieval/deal/types_cbor_gen.go, retrieval/manager.go, retrieval/manager_test.go, retrieval/provider/fsm.go, retrieval/validators.go
This is a very naive approach to payment channel settlement and collection in which:
- We settle after any terminated transfer if we have collected any voucher. If settlement is successful we mark them as settling.
- We iterate through every settling channel at every epoch to check if any is ready to collect. 
Caveats:
- Currently iterate through every stored channel info to find settling channels then iterate again through every settling channel to find any with matching epoch which can get expensive if there are many channels
- We use a local ticker to follow new epochs and may become out of sync with the network epoch if we don't refetch every now and then
=> feat: basic payment channel settlement strategies

exchange/exchange.go, exchange/exchange_test.go, exchange/index.go, exchange/index_cbor_gen.go, exchange/index_test.go, exchange/options.go, exchange/replication.go, exchange/replication_test.go, exchange/tx.go, node/popn.go, retrieval/askstore.go
This updates the Index ranking algorithm to increment new buckets at every read, here is an example of the flow:
The `Interesting` method selects a list of content IDs if any is more popular than the bottom of our local index to fetch every tick. This part is still very hacky and needs to be further tested.
=> feat: fetch popular dags

Makefile
Running ```make``` alone did not work for me, I had to first run ```make build```.
We can add build in the ```all: ```target, or change the Readme to precise to run the ```make build```before ?
=> add build when running make

cmd/pop/cli/start.go, exchange/exchange.go, exchange/exchange_test.go, exchange/options.go, exchange/replication.go, exchange/replication_test.go, node/popn.go
Allows setting the node replication interval in the start options. It is disabled by default as it is still unstable.
=> feat: set replication interval to 0 to deactivate replication job

exchange/replication.go, exchange/replication_test.go
This seems like a better way for waiting for a transfer without having to do gymnastics to check it is the correct transfer. @gallexis maybe try this way on the replication dispatch (replication.go:141)
=> refactor: different way to wait for data transfer events

.gitignore, exchange/exchange.go, exchange/exchange_test.go, exchange/index.go, exchange/index_cbor_gen.go, exchange/index_test.go, exchange/replication.go, exchange/replication_test.go, exchange/tx.go, exchange/tx_test.go, internal/utils/stat.go, node/node_test.go, node/popn.go, retrieval/environments.go, retrieval/gsconfig.go, retrieval/manager.go, retrieval/manager_test.go, testplans/go.mod, testplans/go.sum, testplans/routing.go
- This PR flushes all content from transactions into a global blockstore upon closing. This means that multi stores are only used for a given transaction then discarded when the transaction is completed. 
- The implementer is responsible for adding the transaction ref to the index. I'm still considering adding it by default in the Commit method but it seems decoupling it from the transaction adds more flexibility.
- If the transaction is closed before a transfer succeeds or the transaction is committed the store and all it data will be discarded.
- This blockstore is also the default loaded by the data transfer manager hence any transport configurer will fall back to it if they cannot find a valid multistore for a request.
- In addition, the storage client will also use that blockstore …
=> feat: single blockstore

exchange/peermgr.go, exchange/replication.go, exchange/replication_test.go
Seems like the issue was:
1) The backoff interval didn't leave enough time for all the transfers to complete so it would close the channel before all confirmations came through.
2) The transfers were sometimes too slow for the context timeout and would close before all completed.
=> fix: replication diff regions race

cmd/popp/popp.go, exchange/exchange.go, exchange/exchange_test.go, exchange/hey.go, exchange/options.go, exchange/tx_test.go, node/bls.go, node/node_test.go, node/popn.go, payments/channel.go, payments/channel_test.go, payments/manager_test.go, testplans/go.mod, testplans/go.sum, testplans/replication.go, testplans/routing.go, wallet/wallet.go, wallet/wallet_test.go
The goal of this PR is to remove exchange dependency on the filecoin-ffi so testing is more flexible when using in Testground environments. As a result, any exchange consumer can provide their own wallet interface and register custom signature interfaces. By default the exchange only supports secp256k1 so an external instance must be set in the options to register other signers such as BLS.
=> feat: optional signers

exchange/tx.go, exchange/tx_test.go, internal/utils/stat.go, node/server.go, selectors/sel.go
This allows clients to send a GET request on a transaction root to inspect the content of a transaction before retrieving any keys. The size of each entry is also encoded alongside the content as a way to quickly get an idea of the content size before retrieving it.
=> feat: fetch and list transaction entries without retrieving linked data

cmd/pop/cli/get.go, exchange/exchange.go, exchange/exchange_test.go, exchange/index_test.go, exchange/replication.go, exchange/routing.go, exchange/routing_test.go, exchange/tx.go, exchange/tx_test.go, filecoin/testutils.go, go.mod, internal/testutil/mocknet.go, internal/utils/stat.go, node/message.go, node/node_test.go, node/offermgr.go, node/popn.go, node/server.go, payments/channel.go, payments/channel_test.go, payments/manager.go, payments/manager_test.go, retrieval/askstore.go, retrieval/client/fsm.go, retrieval/deal/types.go, retrieval/deal/types_cbor_gen.go, retrieval/environments.go, retrieval/manager.go, retrieval/manager_test.go, retrieval/validators.go
This is a rather significant amount of changes as progressively retrieving keys required a bit of refactoring.
The aim of this PR is to give the ability to call `Load(<root>)` for retrieving the index of all entries of a given DAG root from a provider and loading the necessary funds to later retrieve parts or all of the DAG. Therefore, the Load RPC allows the following:
- `Load(<root>)` --> Retrieve the index (map with all the keys and entries without resolving the links) and load funds to pay for retrieving all of them with a select provider.
- `Load(<root>/*)` --> Retrieve the index with all linked data
- `Load(<root>/<key>)` --> Retrieve the index and only the linked data for the given key
=> feat: lazy retrievals

go.mod, node/popn.go
ws and tcp are both default transports but I wanted to explicitly declare them so we don't get confused.
=> feat: activate websocket transport

cmd/pop/cli/cli.go, exchange/replication.go, filecoin/lotus.go, internal/utils/repo.go, retrieval/manager_test.go
This is a fix without which the node crashes when trying to get the chain head for channel collection when the lotus RPC cannot connect.
=> fix: return nil when rpc cannot connect

exchange/index.go, exchange/index_test.go
Changed the way we were walking the index to include the index blocks as well
=> fix: do not delete index blocks when cleaning blockstore

build/Dockerfile
- original goreng repo is OOD -- updated to new repository
- as a backup the image has also been pushed to a private AWS container repo
=> fix: update cross compiler image

cmd/bcli/main.go, cmd/pop/cli/start.go, metrics/influxdb_client.go, node/popn.go, node/server.go
Removes any influx methods from pop and add a retrieval record call into the Get method of bcli
=> feat: migrate influxdb to bcli

cmd/pop/cli/start.go, exchange/exchange.go, exchange/options.go, exchange/regions.go, node/popn.go
- remove region-based PPB defaults
- set PPB for delivery via flag
- `Global` region uses EU and USA bootstraps 
- `Global` is now default region
=> refactor: ppb for content delivery as a flag

README.md
Noticed that you can just `go install` pop now, so changed the installation instructions to use that.
Also switched from `commandline` to `console` because that's what seems to be supported by GitHub, and changed some "Github"s to "GitHub"s.
=> doc: Update README installation instructions
