README.md, exchange.go, go.mod, go.sum, options.go
TODO: since we are making the different modules optional users should expect the exchange to function with default modules just by calling `NewExchange(ctx)`. Currently this will cause panic and crash.
=> feat: Functional options and pin blocks to prevent IPFS from gc'ing providing blocks

go.sum, supply/supply.go, supply/supply_test.go
encountered an index out of range issue when filtering out self from peers
=> Fix supply when no peers are available

README.md, exchange.go, exchange_test.go, go.mod, retrieval/manager.go, retrieval/manager_test.go, session.go, supply/supply.go, testutil/mocknet.go
And adding an e2e test with free transfer
=> feat: integrate retrieval module in exchange

Makefile, cmd/hop/cli/add.go, cmd/hop/cli/cli.go, cmd/hop/cli/get.go, cmd/hop/cli/ping.go, cmd/hop/cli/start.go, cmd/hop/hop.go, cmd/hopd/hopd.go, go.mod, go.sum, node/hopn.go, node/message.go, node/server.go, node/socket.go, session.go
Heavily inspired by tailscale cli
=> feat: hop cli

README.md, cmd/hop/cli/add.go, exchange.go, exchange_test.go, node/hopn.go, node/message.go, supply/supply.go, supply/supply_test.go
When adding -dispatch flag to add command, the exchange will attempt to dispatch the content to peers who support the protocol
=> feat(cli): dispatch

cmd/hop/cli/get.go, cmd/hop/cli/ping.go, cmd/hop/cli/start.go, exchange.go, exchange_test.go, filecoin/filecoin.go, filecoin/lotus.go, filecoin/testutils.go, filecoin/types.go, go.mod, go.sum, network.go, network_test.go, node/hopn.go, node/message.go, options.go, payments/channel.go, payments/message.go, payments/store.go, retrieval/client/dtsubscriber.go, retrieval/client/fsm.go, retrieval/deal/status.go, session.go, types.go, types_cbor_gen.go
This allows retrieving from a Filecoin storage miner using `hop get -miner <filecoin-id>`
=> feat(session): Ask storage miner

.github/workflows/go.yml, cmd/pop/cli/get.go, cmd/pop/cli/start.go, node/message.go, node/node_test.go, node/popn.go, node/server.go, node/workdag.go, node/workdag_test.go
This allows resolving a specific file from a DAG archive
=> feat: unpack DAG archive to resolve a file

README.md
=> add docs in readme

exchange.go, exchange_test.go, go.mod, internal/testutil/mocknet.go, node/popn.go, retrieval/deal/types.go, retrieval/deal/types_cbor_gen.go, retrieval/network.go, retrieval/network_test.go, session.go
This still doesn't work as I'd hoped but it should be working enough to move forward
=> fix: rework offer queue and solve gossip publisher ID mismatch

exchange.go, exchange_test.go, go.mod, internal/testutil/mocknet.go, internal/utils/repo.go, retrieval/deal/types.go, retrieval/deal/types_cbor_gen.go, retrieval/network.go, session.go
This allows peers who are not directly connected to dial each other before replying
=> send peer address in gossip msg

cmd/pop/cli/cli.go, cmd/pop/cli/commit.go, cmd/pop/cli/list.go, exchange/index.go, exchange/index_test.go, node/message.go, node/node_test.go, node/popn.go
This PR brings in a variety of fixes as well as a new command to list provided content
=> feat: list refs

exchange/exchange_test.go, exchange/hey.go, exchange/hey_cbor_gen.go, exchange/hey_test.go, exchange/index.go, exchange/index_test.go, exchange/peermgr.go, exchange/replication.go, exchange/replication_cbor_gen.go, exchange/replication_test.go, exchange/selectors.go, exchange/tx.go
For now we only query new indexes on connecting new peers
=> feat: query peer indexes

exchange/discovery_test.go, exchange/exchange.go, exchange/exchange_test.go, exchange/index_test.go, exchange/replication.go, exchange/stat_test.go, exchange/tx.go, exchange/tx_test.go, node/popn.go, retrieval/environments.go, retrieval/manager_test.go, retrieval/validators.go, selectors/sel.go
Also updates Query api to directly pass an ipld.Node selector instead of string
=> feat: selectors pkg

exchange/routing_test.go
=> add TestGossipDuplicateRequests test

exchange/exchange.go, exchange/exchange_test.go, exchange/index.go, exchange/tx.go, exchange/tx_test.go, internal/testutil/mocknet.go, node/popn.go
=> replace putfile() function by put() & modify related tests

exchange/exchange_test.go, exchange/index.go, exchange/index_test.go, exchange/replication.go, exchange/replication_test.go, node/node_test.go, node/popn.go
=> Test: make sure a provider doesn't get dispatched content it's already storing

cmd/pop/cli/start.go, internal/utils/repo.go, node/node_test.go, node/popn.go
=> feat: cli bootstrap parameter handles multi addresses

node/server.go
also add backoff for listen.accept
closes #128
=> Feat: add recover function to avoid exiting program when panicking

cmd/pop/cli/put.go
=> feat: convert filepath in absolute when given in relative

node/server.go
=> set cache RF from http header

cmd/pop/cli/get.go, cmd/pop/cli/start.go, node/popn.go
=> feat: add maxppb flag in survey

cmd/popp/popp.go, exchange/exchange.go, exchange/exchange_test.go, exchange/index.go, exchange/index_test.go, exchange/options.go, exchange/peermgr_test.go, exchange/replication_test.go, exchange/tx.go, go.mod, go.sum, internal/testutil/mocknet.go, internal/utils/stat.go, node/node_test.go, node/popn.go
=> feat: implement garbage collection

cmd/pop/cli/cli.go, cmd/pop/cli/off.go, cmd/pop/cli/ping.go, cmd/pop/cli/start.go, node/message.go, node/popn.go
=> feat: add Off cli

cmd/pop/cli/start.go, node/popn.go
=> feat: add storage capacity in survey

cmd/pop/cli/start.go
This means if all the following flag are provided when starting a node for the first time, no prompt will be asked:
-regions 
-fil-endpoint
-fil-token 
-fil-token-type
-bootstrap 
-capacity 
-maxppb 
-privkey
=> feat: update cli start to skip prompt if all args are provided

filecoin/filecoin.go, filecoin/lotus.go, filecoin/testutils.go, payments/channel.go, payments/manager.go, wallet/wallet.go, wallet/wallet_test.go
This allows the node to work with an HTTPS endpoint too
=> feat: rework waitmsg to poll lotus

node/popn.go
=> feat: add a prefix for dht protocols

testplans/_compositions/baseline_k8s.toml, testplans/_compositions/high_content_replication_k8s.toml, testplans/_compositions/low_content_replication_k8s.toml, testplans/_compositions/network_segment_content_k8s.toml, testplans/_compositions/network_segment_region_k8s.toml, testplans/_compositions/sequential_groups_k8s.toml
- high replication plan for k8s testground
=> feat: sample testplan for k8s

cmd/pop/cli/start.go, go.mod, go.sum
The prompts was annoying me and I didn't find it useful so removed it. We can bring it back if there is evidence users like it but it seems useless.
=> refactor: remove prompts and replace bootstrap address

cmd/pop/cli/start.go
=> fix: switch fil-endpoint to https

node/server.go
This allows usage of port 2001 for gateway TLS requests and p2p TLS requests
=> feat: reroute p2p traffic from 2001

cmd/pop/cli/commit.go, cmd/pop/cli/import.go, exchange/peermgr.go, exchange/replication.go, exchange/replication_test.go, exchange/routing_test.go, internal/utils/repo.go, node/message.go, node/popn.go
=> feat: include given peers into replication set

exchange/exchange.go, exchange/index.go, node/popn.go, selectors/sel.go
Causes issues so probably best to skip it for now
=> fix: remove clean blockstore

cmd/bcli/main.go, cmd/bcli/sw.js
Adds a rough way of reading chrome profiler data. Still need to format it better, it's quite hard to read.
=> feat: bcli basic profiler
